---
  
- name: ensure vhost is present
  become: yes
  become_method: su
  template: src=vhost.j2 dest=/etc/httpd/conf.d/{{ site_domain }}.conf mode=0644
  notify:
    - reload httpd
  tags:
    - apache
    - setup

- name: ensure httpd is started
  become: yes
  become_method: su
  service: name=httpd state=started
  tags:
    - apache
    - setup
