---
  
- name: ensure vhost is present
  become: yes
  template: src=vhost.j2 dest=/etc/apache2/sites-available/{{ site_domain }}.conf mode=0644
  notify:
    - reload apache2
  tags:
    - apache
    - setup
    - sudo

- name: enable vhost
  become: yes
  command: a2ensite {{ site_domain }} creates=/etc/apache2/sites-available/{{ site_domain }}
  notify:
    - reload apache2
  tags:
    - apache
    - setup
    - sudo
