---

- hosts: dev3
  remote_user: dev3
  gather_facts: no
  roles:
    - apache # remove for plesk
    - mysql # remove for blesk
    - application
  vars:
    # Project
    site_name: # Directory where htdocs and application will live
    git_org: elevatedthird # Name of the git user/organization
    git_repo: # Name of the git repository
    drupal_root: site # Dir which has index.php
    git_branch: develop # This is the branch that will be deployed
    max_releases: 10 # Number of past releases to keep

    # Host mysql
    db_name: # name of the db
    db_user: # name of the db user
    db_pass: # db password

    # Host apache
    site_domain: # domain name to put in vhost. Should NOT have www.
    env_vars:
      - dev

    # Host filesystem
    htdocs: httpdocs # document root expected by apache
    htsdocs: httpsdocs # ibid.
    file_owner: dev3
    file_group: apache
    sites_directory: /var/www/vhosts/elevatedthird.com
