---

- hosts: vagrant
  remote_user: vagrant
  gather_facts: no
  sudo: yes
  vars:
    site_name: contrib.e3 # ex. oedit.me
    drupal_root: site # where index.php is, usually site or docroot

    database_name: contrib
    database_user: contrib
    database_pass: elevated
 
  vars_prompt:
    # Notice: setting database_path will overwrite any db you already have on your vagrant instance
    - name: "database_path"
      private: no
      # the prompt shouldn't ever need to be changed.
      prompt: "Vagrant path to db for import"
      # 'none' when there is no db to import, otherwise a path to a local (on vagrant) sql file.
      # Tip: /vagrant_data/pathtoyoursitedir/db.sql
      default: none

  roles:
    - default
