---

- name: reload apache2
  become: yes
  service: name=apache2 state=reloaded
  tags:
    - application
    - launch

- name: apply directory permissions inside repository
  become: yes
  when: ask_become_pass is defined
  command: find . -type d -exec chmod 750 '{}' \+
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}/application/shared/repository"
  tags:
    - application
    - setup
    - deploy
    - sudo
    - permissions

- name: apply files permissions inside repository
  become: yes
  when: ask_become_pass is defined
  command: find . -type f -exec chmod 740 '{}' \+
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}/application/shared/repository"
  tags:
    - application
    - setup
    - deploy
    - sudo
    - permissions
