- name: ensure database is present
  mysql_db: name={{ db_name }} state=present collation=utf8_general_ci login_host={{ item }}
  with_items:
    - localhost
    - 127.0.0.1
  become: yes
  tags:
    - mysql
    - setup
    - sudo

- name: create a database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "{{ db_name }}.*:ALL"
    host: "{{ item }}"
    state: present
    login_host: "{{ item }}"
  with_items:
    - localhost
    - 127.0.0.1
  become: yes
  tags:
    - mysql
    - setup
    - sudo
