---

- name: ensure local settings file is present
  become: yes
  become_method: su
  template:
    src=local-settings.j2
    dest={{ sites_directory }}/{{ site_name }}/application/shared/default/local-settings.inc
    owner={{ file_owner }}
    group={{ file_group }}
    mode=0644
  tags:
    - deploy

- name: get latest application repo
  git:
    dest={{ sites_directory }}/{{ site_name }}/application/shared/repository
    depth=1
    version={{ git_branch }}
    accept_hostkey=yes
    repo=ssh://git@github.com/{{ git_org }}/{{ git_repo }}.git
  tags:
    - deploy
