---

- name: create htdocs symlink
  become: yes
  file:
    path={{ sites_directory }}/{{ site_name }}/{{ htdocs }}
    src={{ sites_directory }}/{{ site_name }}/application/current
    owner={{ file_owner }}
    group={{ file_group }}
    state=link
    force=yes
  notify:
    - reload apache2
  tags:
    - application
    - launch
    - sudo

- name: create htsdocs symlink
  become: yes
  file:
    path={{ sites_directory }}/{{ site_name }}/{{ htsdocs }}
    src={{ sites_directory }}/{{ site_name }}/application/current
    owner={{ file_owner }}
    group={{ file_group }}
    state=link
    force=yes
  notify:
    - reload apache2
  tags:
    - application
    - launch
    - sudo
