---

- name: create directory structure
  become: yes
  file: 
    path={{ sites_directory }}/{{ site_name }}/{{ item.path }}
    owner={{ file_owner }}
    group={{ file_group }}
    mode={{ item.mode }}
    state=directory
  with_items:
    - { path: 'application', mode: '0750' }
    - { path: 'application/shared', mode: '0750' }
    - { path: 'application/shared/default', mode: '0750' }
    - { path: 'application/shared/repository', mode: '0750' }
    - { path: 'application/shared/private', mode: '0770' }
    - { path: 'application/shared/private/tmp', mode: '0770' }
    - { path: 'application/releases', mode: '0750' }
  tags:
    - application
    - setup
    - sudo
    - permissions

- name: provision local settings file
  become: yes
  template:
    src=local-settings.j2
    dest={{ sites_directory }}/{{ site_name }}/application/shared/default/local-settings.inc
    owner={{ file_owner }}
    group={{ file_group }}
    mode=0440
  when: db_pass != "skip"
  tags:
    - application
    - setup
    - settings
    - sudo
    - permissions

- name: ensure htpasswd is present on dev and stage
  become: yes
  command: htpasswd -bc .htpasswd {{ htpasswd_user }} {{ env_var }}
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}"
    creates: "{{ sites_directory }}/{{ site_name }}/.htpasswd"
  when: env_var != "prod"
  notify:
    - reload apache2
  tags:
    - setup
    - sudo
