---

- name: create directory structure
  become: yes
  become_method: sudo
  file: 
    path={{ sites_directory }}/{{ site_name }}/{{ item.path }}
    owner={{ file_owner }}
    group={{ file_group }}
    mode={{ item.mode }}
    state=directory
  with_items:
    - { path: 'application', mode: '0750' }
    - { path: 'application/shared', mode: '0750' }
    - { path: 'application/shared/default', mode: '0750' }
    - { path: 'application/shared/repository', mode: '0750' }
    - { path: 'application/shared/private', mode: '0770' }
    - { path: 'application/shared/private/tmp', mode: '0770' }
    - { path: 'application/releases', mode: '0750' }
  tags:
    - setup
    - sudo
    - permissions

- name: provision local settings file
  become: yes
  become_method: sudo
  template:
    src=local-settings.j2
    dest={{ sites_directory }}/{{ site_name }}/application/shared/default/local-settings.inc
    owner={{ file_owner }}
    group={{ file_group }}
    mode=0440
  tags:
    - setup
    - settings
    - sudo
    - permissions
