---

- name: get latest application repo
  git:
    dest={{ sites_directory }}/{{ site_name }}/application/shared/repository
    version={{ git_branch }}
    accept_hostkey=yes
    force=yes
    recursive=yes
    repo=ssh://{{ git_host }}/{{ git_org }}/{{ git_repo }}.git
  tags:
    - application
    - setup
    - deploy
  notify:
    - apply directory permissions inside repository
    - apply files permissions inside repository

- name: provision settings file
  become: yes
  command: cp {{ sites_directory }}/{{ site_name }}/application/shared/repository/{{ drupal_root }}/sites/default/settings.php {{ sites_directory }}/{{ site_name }}/application/shared/default/settings.php
  tags:
    - application
    - setup
    - settings
    - deploy

- name: set settings file permissions
  become: yes
  file:
    path={{ sites_directory }}/{{ site_name }}/application/shared/default/settings.php
    owner={{ file_owner }}
    group={{ file_group }}
    mode=0440
    state=file
  tags:
    - application
    - setup
    - settings
    - sudo
    - permissions

- name: apply files directory permissions
  become: yes
  file:
    path={{ sites_directory }}/{{ site_name }}/application/shared/default/files
    owner={{ file_owner }}
    group={{ file_group }}
    mode=0770
    state=directory
    recurse=yes
  tags:
    - application
    - setup
    - sudo
    - permissions

- name: apply files permissions inside files directory
  become: yes
  command: find . -type f -exec chmod 660 '{}' \+
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}/application/shared/default/files"
  tags:
    - application
    - setup
    - sudo
    - permissions

- name: apply directory permissions inside files directory
  become: yes
  command: find . -type d -exec chmod 770 '{}' \+
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}/application/shared/default/files"
  tags:
    - application
    - setup
    - sudo
    - permissions

- name: apply ownership inside files directory
  become: yes
  command: find . -exec chown {{ file_owner }}:{{ file_group }} '{}' \+
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}/application/shared/default/files"
  tags:
    - application
    - setup
    - sudo
    - permissions

- name: create latest release
  command: cp -ra {{ sites_directory }}/{{ site_name }}/application/shared/repository/{{ drupal_root }} {{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}
  tags:
    - application
    - deploy
    - release

- name: apply ownership inside docroot
  become: yes
  command: find . -exec chown {{ file_owner }}:{{ file_group }} '{}' \+
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}"
  tags:
    - application
    - deploy
    - release
    #- sudo
    - permissions

- name: remove default directory
  file:
    path={{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}/sites/default
    state=absent
  tags:
    - application
    - deploy
    - release
  
- name: symlink default directory
  file:
    path={{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}/sites/default
    src={{ sites_directory }}/{{ site_name }}/application/shared/default
    force=yes
    state=link
  tags:
    - application
    - deploy
    - release
