---

- name: apply files directory permissions
  become: yes
  become_method: sudo
  file:
    path={{ sites_directory }}/{{ site_name }}/application/shared/default/files
    owner={{ file_owner }}
    group={{ file_group }}
    mode=0775
    state=directory
    recurse=yes
  tags:
    - setup
    - deploy

- name: apply files permissions inside files directory
  become: yes
  become_method: sudo
  command: find . -type f -exec chmod 764 '{}' \+
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}/application/shared/default/files"
  tags:
    - setup
    - deploy

- name: apply directory permissions inside files directory
  become: yes
  become_method: sudo
  command: find . -type d -exec chmod 775 '{}' \+
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}/application/shared/default/files"
  tags:
    - setup
    - deploy

- name: apply ownership inside files directory
  become: yes
  become_method: sudo
  command: find . -exec chown {{ file_owner }}:{{ file_group }} '{}' \+
  args:
    chdir: "{{ sites_directory }}/{{ site_name }}/application/shared/default/files"
  tags:
    - setup
    - deploy

- name: create latest release
  command: cp -ra {{ sites_directory }}/{{ site_name }}/application/shared/repository/{{ drupal_root }} {{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }} 
  tags:
    - deploy
    - release

- name: remove default directory
  file:
    path={{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}/sites/default
    state=absent
  tags:
    - deploy
    - release
  
- name: symlink default directory
  file:
    path={{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}/sites/default
    src={{ sites_directory }}/{{ site_name }}/application/shared/default
    force=yes
    state=link
  tags:
    - deploy
    - release
  
- name: ensure proper release permissions
  become: yes
  become_method: sudo
  file:
    path={{ sites_directory }}/{{ site_name }}/application/releases/{{ timestamp.stdout }}
    owner={{ file_owner }}
    group={{ file_group }}
    mode=0755
    recurse=yes
  tags:
    - deploy
    - release
